version: 2 # use CircleCI 2.0
jobs: # a collection of jobs
  build:
    working_directory: ~/bitwise
    docker: # run build steps with docker
      - image: crystallang/crystal:0.30.1 # primary docker container; all `steps` will run here.
    steps: # a collection of executable steps
      - checkout # checks out source code to working directory
      - run:
          name: Install dependencies.
          command: shards install
      - run:
          name: test
          command: crystal spec
# See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
